### ISSUE TITLE
Create opendata.swiss profile

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-link#118]
We need validation of cubes which should be visible on opendata.swiss. So far I determined these properties are used:

1. `dcterms:accrualPeriodicity`
2. `dcterms:identifier`
3. `dcterms:creator`

What else? @l00mi @ktk @ludovicm67

**Comment by ludovicm67** [comment]
The CKAN Trifid plugin README page is listing many of them already: https://github.com/zazuko/trifid/tree/main/packages/ckan

**Comment by ludovicm67** [comment]
This might also be useful https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe/distribution/dcat-ap-200-shacl-shapes

**Comment by tpluscode** [comment]
Good one. If only they made these shapes dereferencable
