### ISSUE TITLE
Path to labels for IRI observation values

### ISSUE THREAD

**Issue by bergos** [zazuko/cube-link#42]
Visualizations may want to use labels for IRI values of observations. A path to the label could be stored in the property shape of the dimension. Besides the path, the available languages should be stored.

Here is an example how it could look like:

```turtle
[
  schema:name "Room"@en, "Raum"@de , "Pièce"@fr ;
  sh:path dh:room ;
  meta:labelLocation [
    meta:labelPath (schema:location schema:address schema:name);
    meta:labelLanguage "en", "de", ""
  ]
].
```

The nested structure can be used to share the location of the label like shown in this example:

```turtle
<roomLabelLocation>
  meta:labelPath (schema:location schema:address schema:name);
  meta:labelLanguage "en", "de", "".

[
  schema:name "Room"@en, "Raum"@de , "Pièce"@fr ;
  sh:path dh:room ;
  meta:labelLocation <roomLabelLocation>
].
```

If no location for the label is given, optional fallbacks like `schema:name` or `rdfs:label` could be defined. The optional could ruin the query performance. Therefore the information about not having a label has some value. It can be described with a location pointing to `cube:Undefined` like in the following example:

```turtle
[
  schema:name "Room"@en, "Raum"@de , "Pièce"@fr ;
  sh:path dh:room ;
  meta:labelLocation cube:Undefined
].
```

**Comment by l00mi** [comment]
@bergos ?
