### ISSUE TITLE
Update build process

### ISSUE THREAD

**Issue by semanticfire** [zazuko/cube-link#85]
To properly publish the spec the following modifications need to be made during the build process:
* in every `config.js` replace `ZZ-DRAFT`with `ZZ-BASIC`
* in every `index.html` remove `<section id='issue-summary'></section>`

**Comment by ludovicm67** [comment]
Should be OK now.

I explicitly listed the files where to do the changes to avoid any issue.
Impacted files are `config.js` and `index.html` in `/` `/meta` and `/relation`.

**Comment by ludovicm67** [comment]
The new deployed version seems to be fine.

@semanticfire can you also quickly check if everything looks as expected?
If so, can you close this issue?
