### ISSUE TITLE
Align the name of this repository to cube.link

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-link#88]
Change all mentions of rdf-cube-schema: https://github.com/zazuko/rdf-cube-schema/search?q=rdf-cube-schema&type=code
to reflect the global name, cube.link ... by changing to cube-link.

**Comment by semanticfire** [comment]
Also update the naming accordingly, use Cube.link Schema instead of RDF Cube Schema

**Comment by semanticfire** [comment]
Massive update here: e177766df91c4e5a7c77eb68145d23c8c10710e0

**Comment by semanticfire** [comment]
All done
