### ISSUE TITLE
Consider adding `sh:targetClass cube:Observation` to shape

### ISSUE THREAD

**Issue by kronmar** [zazuko/cube-link#90]
The example shape (`constraint.ttl`) you currently have does not constrain the cube (`cube.ttl`).

If it's intended, that the constraint actually targets the observation in the cube, one should add a `sh:targetClass cube:Observation` to the shape. As it stands now, one could change anything in `constraint.ttl` without ever producing a failed validation when using 
```
.\bin\cube-link.js validate cube.ttl constraint.ttl
```
to validate this example cube as described on the draft wiki.

**Comment by Rdataflow** [comment]
@kronmar wanna close this? - should be solved now
