### ISSUE TITLE
Versioning and deployment of cube.link shapes

### ISSUE THREAD

**Issue by tpluscode** [zazuko/cube-link#94]
What is the current story for accessing and using the shapes in applications?

For the time being, I run validation using Jena's SPARQL CLI by directly dereferencing from raw github URLs.

```
shacl v --shapes https://raw.githubusercontent.com/zazuko/cube-link/v0.0.4/validation/standalone-cube-constraint.ttl
```

This works for now but in the long run we discussed that these shapes would have to be more easily deployed as we introduce changes and more easily accessible

I propose two deployments: 
- on NPM 
- dereferencable from cube.link

For cube.link, since trifid is used to serve, I would propose to add a simple redirect from like `https://cube.link/{version}/shape/standalone-cube-constraint` to `raw.githubusercontent.com` URLs. Might even try to skip the `{version}` segment if we can on-the-fly determine the latest tag. Would be easy if we automated the creation of github releases and redirect to these instead

NPM would not be rocket science. :)

**Comment by tpluscode** [comment]
Are we giving up the NPM deployment? @ludovicm67 @giacomociti

**Comment by ludovicm67** [comment]
I don't think it's required as tools are going over cube.link directly

**Comment by tpluscode** [comment]
Ok, let me close for now until we decide to use NPM after all
